/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.carrepairservicemanagementsystem.panels;

import com.mycompany.carrepairservicemanagementsystem.models.Inventory;
import java.awt.*;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author emiryncr
 */
public class inventoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form inventoryPanel
     */
    public inventoryPanel() {
        initComponents();
        
        jTable1.getColumnModel().getColumn(jTable1.getColumnCount() - 1) 
        .setCellRenderer(new ButtonRendererInventory());
        jTable1.getColumnModel().getColumn(jTable1.getColumnCount() - 1)
        .setCellEditor(new ButtonEditorInventory(new JCheckBox(), jTable1, this));
        
        jTable1.getColumnModel().getColumn(jTable1.getColumnCount() - 1)
        .setPreferredWidth(200);
        jTable1.setRowHeight(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPartId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPartName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPartNo = new javax.swing.JTextField();
        txtCategory = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Inventory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setText("Part ID");

        jLabel2.setText("Part  Name");

        jLabel3.setText("Part No");

        jLabel4.setText("Category");

        jLabel5.setText("Stock Quantity");

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        ClearBtn.setText("Clear");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPartId)
                            .addComponent(txtPartName)
                            .addComponent(txtPartNo)
                            .addComponent(txtCategory)
                            .addComponent(txtStock)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClearBtn)
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPartId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPartName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPartNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(updateBtn)
                    .addComponent(ClearBtn))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Part ID", "Part Name", "Part No", "Category", "Stock Quantity", "Actions"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(txtPartId.getText());
            String iName = txtPartName.getText();
            String iPartNo = txtPartNo.getText();
            String iCat = txtCategory.getText();
            int iStock = Integer.parseInt(txtStock.getText());
                
            //Inventory.add_inventory_item(id,iName,iPartNo,iCat,iStock);
            boolean dbSuccess = Inventory.addInventoryToDB(id, iName, iPartNo, iCat, iStock);
            if (!dbSuccess) {
                JOptionPane.showMessageDialog(this, "Failed to save inventory item to database!");
            }
            
            updateTable();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something went wrong: " + e.getMessage());
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
            try {
            int id = Integer.parseInt(txtPartId.getText());
            //Inventory existing = Inventory.get_inventory_by_id(id);
            Inventory existing = Inventory.getInventoryFromDB(id);
            if (existing == null) {
                JOptionPane.showMessageDialog(this, "Inventory item not found!");
                return;
            }

            String iName = txtPartName.getText().isEmpty() ? existing.get_part_name(): txtPartName.getText();
            String iPartNo = txtPartNo.getText().isEmpty() ? existing.get_part_number(): txtPartNo.getText();
            String iCat = txtCategory.getText().isEmpty() ? existing.get_category(): txtCategory.getText();
            int iStock = txtStock.getText().isEmpty() ? existing.get_quantity_in_stock(): Integer.parseInt(txtStock.getText());

            //Inventory.edit_inventory_item(id,iName,iPartNo,iCat,iStock);
            boolean dbSuccess = Inventory.editInventoryInDB(id, iName, iPartNo, iCat, iStock);
            if (!dbSuccess) {
                JOptionPane.showMessageDialog(this, "Failed to update inventory item in database!");
            }
            
            updateTable();

        JOptionPane.showMessageDialog(this, "Inventory updated!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something went wrong: " + e.getMessage());
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        // TODO add your handling code here:
        txtPartId.setText("");
        txtPartName.setText("");
        txtPartNo.setText("");
        txtCategory.setText("");
        txtStock.setText("");
    }//GEN-LAST:event_ClearBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtPartId;
    private javax.swing.JTextField txtPartName;
    private javax.swing.JTextField txtPartNo;
    private javax.swing.JTextField txtStock;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

    public void updateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); 
        
        //Map.Entry<Integer, Inventory> entry : Inventory.get_all_inventories().entrySet()
        ArrayList<Inventory> inventoryItems = Inventory.getAllInventoryFromDB();
        for (Inventory i : inventoryItems) {
            //Inventory i = entry.getValue();

            Object[] row = {
                i.get_part_id(),
                i.get_part_name(),
                i.get_part_number(),
                i.get_category(),
                i.get_quantity_in_stock()
            };
            model.addRow(row);
        }
    }
}

class ButtonRendererInventory extends JButton implements TableCellRenderer {
    private final JPanel panel;
    private final JButton btnDelete;
    
    public ButtonRendererInventory() {
        panel = new JPanel(new FlowLayout(FlowLayout.CENTER, 5, 0)); 

        btnDelete = new JButton("Delete");
        btnDelete.setFont(new Font("Segoe UI", Font.BOLD, 12));
        btnDelete.setBackground(new Color(220, 53, 69)); 
        btnDelete.setForeground(Color.WHITE);
        btnDelete.setFocusPainted(false);
        btnDelete.setMargin(new Insets(2, 5, 2, 5)); 

        panel.add(btnDelete);
        panel.setBackground(null); 
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {
        if (isSelected) {
            panel.setBackground(table.getSelectionBackground());
        } else {
            panel.setBackground(table.getBackground());
        }
        return panel;
    }
}

// Makes the button clickable
class ButtonEditorInventory extends DefaultCellEditor {
    private final JPanel panel;
    private final JButton btnDelete;
    private final JTable table;
    private final inventoryPanel inventoryPanel;
    private int selectedRow;
    
    public ButtonEditorInventory(JCheckBox checkBox, JTable table, inventoryPanel inventoryPanel) {
        super(checkBox);
        this.table = table;
        this.inventoryPanel = inventoryPanel;
        panel = new JPanel(new FlowLayout(FlowLayout.CENTER, 5, 0));
        
        btnDelete = new JButton("Delete");
        btnDelete.setFont(new Font("Segoe UI", Font.BOLD, 12));
        btnDelete.setBackground(new Color(220, 53, 69));
        btnDelete.setForeground(Color.WHITE);
        btnDelete.setFocusPainted(false);
        btnDelete.setMargin(new Insets(2, 5, 2, 5));
        
        btnDelete.addActionListener(e -> {
            fireEditingStopped();
            
            try {
                if (selectedRow < 0 || selectedRow >= table.getRowCount()) {
                    JOptionPane.showMessageDialog(
                        SwingUtilities.getWindowAncestor(table),
                        "Invalid row selection.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                    );
                    return;
                }
                
                int id = (int) table.getValueAt(selectedRow, 0);
                
                int response = JOptionPane.showConfirmDialog(
                    SwingUtilities.getWindowAncestor(table),
                    "Are you sure you want to delete inventory item: " + id + "?",
                    "Confirm Deletion",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
                );
                
                if (response == JOptionPane.YES_OPTION) {
                    //Inventory.delete_inventory_item(id);
                    
                    //DefaultTableModel model = (DefaultTableModel) table.getModel();
                    //model.removeRow(selectedRow);
                    
                    boolean dbSuccess = Inventory.deleteInventoryFromDB(id);
                    if (!dbSuccess) {
                        JOptionPane.showMessageDialog(
                            SwingUtilities.getWindowAncestor(table),
                            "Failed to delete inventory item from database!",
                            "Database Error",
                            JOptionPane.ERROR_MESSAGE
                        );
                    }
                    
                    System.out.println("Deleted inventory item with ID: " + id);
                    
                    inventoryPanel.updateTable();
                    //table.revalidate();
                    //table.repaint();
                }
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(
                    SwingUtilities.getWindowAncestor(table),
                    "Error deleting inventory item: " + ex.getMessage(),
                    "Deletion Error",
                    JOptionPane.ERROR_MESSAGE
                );
                ex.printStackTrace();
            }
        });
        
        panel.add(btnDelete);
        panel.setBackground(null);
    }
    
    @Override
    public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
        this.selectedRow = row;
        
        if (isSelected) {
            panel.setBackground(table.getSelectionBackground());
        } else {
            panel.setBackground(table.getBackground());
        }
        
        return panel;
    }
    
    @Override
    public Object getCellEditorValue() {
        return "";
    }
    
    @Override
    public boolean stopCellEditing() {
        return super.stopCellEditing();
    }
}