/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.carrepairservicemanagementsystem.panels;

import com.mycompany.carrepairservicemanagementsystem.models.OrderItem;
import java.awt.*;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author emiryncr
 */
public class orderItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form orderItemPanel
     */
    public orderItemPanel() {
        initComponents();
        
        jTable1.getColumnModel().getColumn(jTable1.getColumnCount() - 1) 
        .setCellRenderer(new ButtonRendererOrderItem());
        jTable1.getColumnModel().getColumn(jTable1.getColumnCount() - 1)
        .setCellEditor(new ButtonEditorOrderItem(new JCheckBox(), jTable1, this));
        
        jTable1.getColumnModel().getColumn(jTable1.getColumnCount() - 1)
        .setPreferredWidth(200);
        jTable1.setRowHeight(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtItemId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtOrderId = new javax.swing.JTextField();
        txtPartID = new javax.swing.JTextField();
        txtServDesc = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtUnitPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Order Item", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setText("Item ID");

        jLabel2.setText("Order ID");

        jLabel3.setText("Part ID");

        jLabel4.setText("Service Description");

        jLabel5.setText("Quantity");

        jLabel6.setText("Unit Price");

        jLabel7.setText("Line Total");

        jLabel8.setText("Will create automatically");

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtItemId)
                            .addComponent(txtOrderId)
                            .addComponent(txtPartID)
                            .addComponent(txtUnitPrice)
                            .addComponent(txtQuantity)
                            .addComponent(txtServDesc)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtItemId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPartID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtServDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(updateBtn)
                    .addComponent(clearBtn))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Order ID", "Part ID", "Service Description", "Quantity", "Unit Price", "Line Total", "Actions"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        try {
            int orderItemId = Integer.parseInt(txtItemId.getText());
            int orderId = Integer.parseInt(txtOrderId.getText());
            int partId = Integer.parseInt(txtPartID.getText());
            String serviceDescription = txtServDesc.getText();
            int quantity = Integer.parseInt(txtQuantity.getText());
            float unitPrice = Float.parseFloat(txtUnitPrice.getText());

            if (serviceDescription.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Service description cannot be empty.");
                return;
            }

            //OrderItem.add_order_item(orderItemId, orderId, partId, serviceDescription, quantity, unitPrice);

            float lineTotal = OrderItem.calculate_line_total(quantity, unitPrice);
            boolean dbSuccess = OrderItem.addOrderItemToDB(orderItemId, orderId, partId, 
                                                         serviceDescription, quantity, 
                                                         unitPrice, lineTotal);
            if (!dbSuccess) {
                JOptionPane.showMessageDialog(this, "Failed to save order item to database!");
            }
            
            updateTable(); 
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid number format: " + ex.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something went wrong: " + e.getMessage());
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(txtItemId.getText());
            //OrderItem existing = OrderItem.get_order_item_by_id(id);

            OrderItem existing = OrderItem.getOrderItemFromDB(id);
            if (existing == null) {
                JOptionPane.showMessageDialog(this, "Order item not found!");
                return;
            }

            int orderId = existing.get_order_id();
            int partId = Integer.parseInt(txtPartID.getText());
            String serviceDescription = txtServDesc.getText().isEmpty() ? existing.get_service_description() : txtServDesc.getText();
            int quantity = txtQuantity.getText().isEmpty() ? existing.get_quantity() : Integer.parseInt(txtQuantity.getText());
            float unitPrice = txtUnitPrice.getText().isEmpty() ? existing.get_unit_price() : Float.parseFloat(txtUnitPrice.getText());

            float lineTotal = quantity * unitPrice;
            //OrderItem.edit_order_item(id, orderId, partId, serviceDescription, quantity, unitPrice, lineTotal);
            
            boolean dbSuccess = OrderItem.editOrderItemInDB(id, orderId, partId, 
                                              serviceDescription, quantity, 
                                              unitPrice, lineTotal);
            if (!dbSuccess) {
                JOptionPane.showMessageDialog(this, "Failed to update order item in database!");
            }
            
            updateTable();
            JOptionPane.showMessageDialog(this, "Order item updated successfully.");

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid number format: " + ex.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something went wrong: " + e.getMessage());
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        txtItemId.setText("");
        txtOrderId.setText("");
        txtPartID.setText("");
        txtServDesc.setText("");
        txtQuantity.setText("");
        txtUnitPrice.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtItemId;
    private javax.swing.JTextField txtOrderId;
    private javax.swing.JTextField txtPartID;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtServDesc;
    private javax.swing.JTextField txtUnitPrice;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
    
    public void updateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); 
        //Map.Entry<Integer, OrderItem> entry : OrderItem.get_all_order_items().entrySet()
        ArrayList<OrderItem> orderItems = OrderItem.getAllOrderItemsFromDB();
        for (OrderItem o : orderItems) {
            //OrderItem o = entry.getValue();

            Object[] row = {
                o.get_order_item_id(),
                o.get_order_id(),
                o.get_part_id(),
                o.get_service_description(),
                o.get_quantity(),
                o.get_unit_price(),
                o.get_line_total()
            };
            model.addRow(row);
        }
    }
}

class ButtonRendererOrderItem extends JButton implements TableCellRenderer {
    private final JPanel panel;
    private final JButton btnDelete;
    
    public ButtonRendererOrderItem() {
        panel = new JPanel(new FlowLayout(FlowLayout.CENTER, 5, 0)); 

        btnDelete = new JButton("Delete");
        btnDelete.setFont(new Font("Segoe UI", Font.BOLD, 12));
        btnDelete.setBackground(new Color(220, 53, 69)); 
        btnDelete.setForeground(Color.WHITE);
        btnDelete.setFocusPainted(false);
        btnDelete.setMargin(new Insets(2, 5, 2, 5)); 

        panel.add(btnDelete);
        panel.setBackground(null); 
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {
        if (isSelected) {
            panel.setBackground(table.getSelectionBackground());
        } else {
            panel.setBackground(table.getBackground());
        }
        return panel;
    }
}

// Makes the button clickable
class ButtonEditorOrderItem extends DefaultCellEditor {
    private final JPanel panel;
    private final JButton btnDelete;
    private final JTable table;
    private final orderItemPanel orderItemPanel;
    private int selectedRow;
    
    public ButtonEditorOrderItem(JCheckBox checkBox, JTable table, orderItemPanel orderItemPanel) {
        super(checkBox);
        this.table = table;
        this.orderItemPanel = orderItemPanel;
        panel = new JPanel(new FlowLayout(FlowLayout.CENTER, 5, 0));
        
        btnDelete = new JButton("Delete");
        btnDelete.setFont(new Font("Segoe UI", Font.BOLD, 12));
        btnDelete.setBackground(new Color(220, 53, 69));
        btnDelete.setForeground(Color.WHITE);
        btnDelete.setFocusPainted(false);
        btnDelete.setMargin(new Insets(2, 5, 2, 5));
        
        btnDelete.addActionListener(e -> {
            fireEditingStopped();
            
            try {
                if (selectedRow < 0 || selectedRow >= table.getRowCount()) {
                    JOptionPane.showMessageDialog(
                        SwingUtilities.getWindowAncestor(table),
                        "Invalid row selection.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                    );
                    return;
                }
                
                int id = (int) table.getValueAt(selectedRow, 0);
                
                int response = JOptionPane.showConfirmDialog(
                    SwingUtilities.getWindowAncestor(table),
                    "Are you sure you want to delete order item: " + id + "?",
                    "Confirm Deletion",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
                );
                
                if (response == JOptionPane.YES_OPTION) {
                    //OrderItem.delete_order_item(id);
                    
                   // DefaultTableModel model = (DefaultTableModel) table.getModel();
                    //model.removeRow(selectedRow);
                    
                    boolean dbSuccess = OrderItem.deleteOrderItemFromDB(id);
                    if (!dbSuccess) {
                        JOptionPane.showMessageDialog(
                            SwingUtilities.getWindowAncestor(table),
                            "Failed to delete order item from database!",
                            "Database Error",
                            JOptionPane.ERROR_MESSAGE
                        );
                    }
                    
                    System.out.println("Deleted order item with ID: " + id);
                    
                    orderItemPanel.updateTable();
                    
                    //table.revalidate();
                    //table.repaint();
                }
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(
                    SwingUtilities.getWindowAncestor(table),
                    "Error deleting order item: " + ex.getMessage(),
                    "Deletion Error",
                    JOptionPane.ERROR_MESSAGE
                );
                ex.printStackTrace();
            }
        });
        
        panel.add(btnDelete);
        panel.setBackground(null);
    }
    
    @Override
    public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
        this.selectedRow = row;
        
        if (isSelected) {
            panel.setBackground(table.getSelectionBackground());
        } else {
            panel.setBackground(table.getBackground());
        }
        
        return panel;
    }
    
    @Override
    public Object getCellEditorValue() {
        return "";
    }
    
    @Override
    public boolean stopCellEditing() {
        return super.stopCellEditing();
    }
}

