/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.carrepairservicemanagementsystem.panels;

import com.mycompany.carrepairservicemanagementsystem.models.ServiceOrder;
import java.awt.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.Map;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author emiryncr
 */
public class serviceOrderPanel extends javax.swing.JPanel {

    /**
     * Creates new form serviceOrderPanel
     */
    public serviceOrderPanel() {
        initComponents();
        
        jTable1.getColumnModel().getColumn(jTable1.getColumnCount() - 1) 
        .setCellRenderer(new ButtonRendererService());
        jTable1.getColumnModel().getColumn(jTable1.getColumnCount() - 1)
        .setCellEditor(new ButtonEditorService(new JCheckBox(), jTable1, this));
        
        jTable1.getColumnModel().getColumn(jTable1.getColumnCount() - 1)
        .setPreferredWidth(200);
        jTable1.setRowHeight(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtOrderId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtVehicleId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        txtTotalCost = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        txtStatusCheck = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Service", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setText("Order ID");

        jLabel2.setText("Vehicle ID");

        jLabel3.setText("Date Received");

        jLabel4.setText("Date Completed");

        jLabel5.setText("Status");

        jLabel6.setText("Description");

        jLabel7.setText("Total Cost");

        jLabel8.setText("Will create automatically");

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        txtStatusCheck.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "In Progress", "Completed" }));

        jLabel10.setText("Will create automatically");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(txtVehicleId)
                                    .addComponent(txtDesc)
                                    .addComponent(txtTotalCost)
                                    .addComponent(txtStatusCheck, 0, 156, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtVehicleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtStatusCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(updateBtn)
                    .addComponent(clearBtn))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Vehicle ID", "Date Received", "Date Completed", "Status", "Description", "Total Cost", "Actions"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(txtOrderId.getText());
            int vId = Integer.parseInt(txtVehicleId.getText());

            Date sReceived = new Date();

            String status = txtStatusCheck.getSelectedItem().toString();

            
            Date sCompleted = status.equals("Completed") ? new Date() : null;

            String desc = txtDesc.getText();
            float cost = Float.parseFloat(txtTotalCost.getText());

            //ServiceOrder.add_service_order(id, vId, sReceived, sCompleted, status, desc, cost);
            boolean dbSuccess = ServiceOrder.addServiceOrderToDB(id, vId, sReceived, sCompleted, status, desc, cost);
            if (!dbSuccess) {
                JOptionPane.showMessageDialog(this, "Failed to save service order to database!");
            }
            updateTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something went wrong: " + e.getMessage());
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(txtOrderId.getText());
            //ServiceOrder existing = ServiceOrder.get_service_by_id(id);
            ServiceOrder existing = ServiceOrder.getServiceOrderFromDB(id);
            if (existing == null) {
                JOptionPane.showMessageDialog(this, "Service order not found!");
                return;
            }
            
            int vId = existing.get_vehicle_id();
                    
            Date received = existing.get_date_received(); 
            String selectedStatus = txtStatusCheck.getSelectedItem().toString();
            String status = selectedStatus.isEmpty() ? existing.get_status() : selectedStatus;

            Date completed = status.equals("Completed") ? new Date() : existing.get_date_completed();

            
            String desc = txtDesc.getText().isEmpty() ? existing.get_description() : txtDesc.getText();
            float cost = txtTotalCost.getText().isEmpty() ? existing.get_total_cost(): Float.parseFloat(txtTotalCost.getText());

            //ServiceOrder.edit_service_order(id, vId, received, completed, status, desc, cost);
            boolean dbSuccess = ServiceOrder.editServiceOrderInDB(id, vId, received, completed, status, desc, cost);
            if (!dbSuccess) {
                JOptionPane.showMessageDialog(this, "Failed to update service order in database!");
            }
            updateTable();
            JOptionPane.showMessageDialog(this, "Service order updated!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something went wrong: " + e.getMessage());
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        txtOrderId.setText("");
        txtVehicleId.setText("");
        txtStatusCheck.setAction(null);
        txtDesc.setText("");
        txtTotalCost.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtOrderId;
    private javax.swing.JComboBox<String> txtStatusCheck;
    private javax.swing.JTextField txtTotalCost;
    private javax.swing.JTextField txtVehicleId;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
    
    public void updateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); 
        //Map.Entry<Integer, ServiceOrder> entry : ServiceOrder.get_all_services().entrySet()
        ArrayList<ServiceOrder> serviceOrders = ServiceOrder.getAllServiceOrdersFromDB();
        for (ServiceOrder s : serviceOrders) {
            //ServiceOrder s = entry.getValue();

            Object[] row = {
                s.get_order_id(),
                s.get_vehicle_id(),
                s.get_date_received(),
                s.get_date_completed(),
                s.get_status(),
                s.get_description(),
                s.get_total_cost()
            };
            model.addRow(row);
        }
    }
}

class ButtonRendererService extends JButton implements TableCellRenderer {
    private final JPanel panel;
    private final JButton btnDelete;
    
    public ButtonRendererService() {
        panel = new JPanel(new FlowLayout(FlowLayout.CENTER, 5, 0)); 

        btnDelete = new JButton("Delete");
        btnDelete.setFont(new Font("Segoe UI", Font.BOLD, 12));
        btnDelete.setBackground(new Color(220, 53, 69)); 
        btnDelete.setForeground(Color.WHITE);
        btnDelete.setFocusPainted(false);
        btnDelete.setMargin(new Insets(2, 5, 2, 5)); 

        panel.add(btnDelete);
        panel.setBackground(null); 
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {
        if (isSelected) {
            panel.setBackground(table.getSelectionBackground());
        } else {
            panel.setBackground(table.getBackground());
        }
        return panel;
    }
}

// Makes the button clickable
class ButtonEditorService extends DefaultCellEditor {
    private final JPanel panel;
    private final JButton btnDelete;
    private final JTable table;
    private final serviceOrderPanel serviceOrderPanel;
    private int selectedRow;
    
    public ButtonEditorService(JCheckBox checkBox, JTable table, serviceOrderPanel serviceOrderPanel) {
        super(checkBox);
        this.table = table;
        this.serviceOrderPanel = serviceOrderPanel;
        panel = new JPanel(new FlowLayout(FlowLayout.CENTER, 5, 0));
        
        btnDelete = new JButton("Delete");
        btnDelete.setFont(new Font("Segoe UI", Font.BOLD, 12));
        btnDelete.setBackground(new Color(220, 53, 69));
        btnDelete.setForeground(Color.WHITE);
        btnDelete.setFocusPainted(false);
        btnDelete.setMargin(new Insets(2, 5, 2, 5));
        
        btnDelete.addActionListener(e -> {
            fireEditingStopped();
            
            try {
                if (selectedRow < 0 || selectedRow >= table.getRowCount()) {
                    JOptionPane.showMessageDialog(
                        SwingUtilities.getWindowAncestor(table),
                        "Invalid row selection.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                    );
                    return;
                }
                
                int id = (int) table.getValueAt(selectedRow, 0);
                
                int response = JOptionPane.showConfirmDialog(
                    SwingUtilities.getWindowAncestor(table),
                    "Are you sure you want to delete service order: " + id + "?",
                    "Confirm Deletion",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
                );
                
                if (response == JOptionPane.YES_OPTION) {
                    //ServiceOrder.delete_service_order(id);
                    
                    //DefaultTableModel model = (DefaultTableModel) table.getModel();
                    //model.removeRow(selectedRow);
                    
                    boolean dbSuccess = ServiceOrder.deleteServiceOrderFromDB(id);
                    if (!dbSuccess) {
                        JOptionPane.showMessageDialog(
                            SwingUtilities.getWindowAncestor(table),
                            "Failed to delete service order from database!",
                            "Database Error",
                            JOptionPane.ERROR_MESSAGE
                        );
                    }
                    
                    System.out.println("Deleted service order with ID: " + id);
                    
                    serviceOrderPanel.updateTable();
                    //table.revalidate();
                    //table.repaint();
                }
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(
                    SwingUtilities.getWindowAncestor(table),
                    "Error deleting service order: " + ex.getMessage(),
                    "Deletion Error",
                    JOptionPane.ERROR_MESSAGE
                );
                ex.printStackTrace();
            }
        });
        
        panel.add(btnDelete);
        panel.setBackground(null);
    }
    
    @Override
    public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
        this.selectedRow = row;
        
        if (isSelected) {
            panel.setBackground(table.getSelectionBackground());
        } else {
            panel.setBackground(table.getBackground());
        }
        
        return panel;
    }
    
    @Override
    public Object getCellEditorValue() {
        return "";
    }
    
    @Override
    public boolean stopCellEditing() {
        return super.stopCellEditing();
    }
}
