/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.carrepairservicemanagementsystem.panels;

import com.mycompany.carrepairservicemanagementsystem.models.Vehicle;
import java.awt.Color;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Insets;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author emiryncr
 */
public class vehiclePanel extends javax.swing.JPanel {

    /**
     * Creates new form vehiclePanel
     */
    public vehiclePanel() {
        initComponents();
        
        jTable1.getColumnModel().getColumn(jTable1.getColumnCount() - 1) 
        .setCellRenderer(new ButtonRendererVehicle());
        jTable1.getColumnModel().getColumn(jTable1.getColumnCount() - 1)
        .setCellEditor(new ButtonEditorVehicle(new JCheckBox(), jTable1, this));
        
        jTable1.getColumnModel().getColumn(jTable1.getColumnCount() - 1)
        .setPreferredWidth(200);
        jTable1.setRowHeight(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtVehicleId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCustId = new javax.swing.JTextField();
        txtMake = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtVin = new javax.swing.JTextField();
        txtPlate = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel9.setText("jLabel9");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Vehicle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setText("Vehicle ID");

        jLabel2.setText("Customer ID");

        jLabel3.setText("Make");

        jLabel4.setText("Model");

        jLabel5.setText("Year");

        jLabel6.setText("VIN");

        jLabel7.setText("Plate");

        jLabel8.setText("Color");

        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearBtn)
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtColor)
                            .addComponent(txtPlate)
                            .addComponent(txtVin)
                            .addComponent(txtYear)
                            .addComponent(txtMake)
                            .addComponent(txtVehicleId)
                            .addComponent(txtCustId)
                            .addComponent(txtModel, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtVehicleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCustId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtVin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(updateBtn)
                    .addComponent(clearBtn))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle ID", "Customer ID", "Make ", "Model", "Year", "VIN", "Plate", "Color", "Actions"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(txtVehicleId.getText());
            //Vehicle existing = Vehicle.get_vehicle_by_id(id);
            Vehicle existing = Vehicle.getVehicleFromDB(id);
            if (existing == null) {
                JOptionPane.showMessageDialog(this, "Vehicle not found!");
                return;
            }

            int cId = existing.get_customer_id();
            String vMake = txtMake.getText().isEmpty() ? existing.get_make(): txtMake.getText();
            String vModel = txtModel.getText().isEmpty() ? existing.get_model(): txtModel.getText();
            int vYear = txtYear.getText().isEmpty() ? existing.get_year() : Integer.parseInt(txtYear.getText());
            String vVin = txtVin.getText().isEmpty() ? existing.get_vin(): txtVin.getText();
            String vPlate = txtPlate.getText().isEmpty() ? existing.get_license_plate(): txtPlate.getText();
            String vColor = txtColor.getText().isEmpty() ? existing.get_color(): txtColor.getText();

            //Vehicle.edit_vehicle(id,cId,vMake,vModel,vYear,vVin,vPlate,vColor);
            boolean dbSuccess = Vehicle.editVehicleInDB(id, cId, vMake, vModel, vYear, vVin, vPlate, vColor);
            if (!dbSuccess) {
                JOptionPane.showMessageDialog(this, "Failed to save vehicle to database!");
            }
            updateTable();

        JOptionPane.showMessageDialog(this, "Vehicle updated!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something went wrong: " + e.getMessage());
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(txtVehicleId.getText());
            int cId = Integer.parseInt(txtCustId.getText());
            String vMake = txtMake.getText();
            String vModel = txtModel.getText();
            int vYear = Integer.parseInt(txtYear.getText());
            String vVin = txtVin.getText();
            String vPlate = txtPlate.getText();
            String vColor = txtColor.getText();
                
            //Vehicle.add_vehicle(id,cId,vMake,vModel,vYear,vVin,vPlate,vColor);
            boolean dbSuccess = Vehicle.addVehicleToDB(id, cId, vMake, vModel, vYear, vVin, vPlate, vColor);
            if (!dbSuccess) {
                JOptionPane.showMessageDialog(this, "Failed to save vehicle to database!");
            }
            updateTable();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something went wrong: " + e.getMessage());
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        txtVehicleId.setText("");
        txtMake.setText("");
        txtModel.setText("");
        txtYear.setText("");       
        txtVin.setText("");     
        txtPlate.setText("");     
        txtColor.setText("");  
        txtCustId.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtCustId;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPlate;
    private javax.swing.JTextField txtVehicleId;
    private javax.swing.JTextField txtVin;
    private javax.swing.JTextField txtYear;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

    public void updateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); 
        //Map.Entry<Integer, Vehicle> entry : Vehicle.get_all_vehicles().entrySet()
        ArrayList<Vehicle> vehicles = Vehicle.getAllVehiclesFromDB();
        for (Vehicle v : vehicles) {
            //Vehicle v = entry.getValue();

            Object[] row = {
                v.get_vehicle_id(),
                v.get_customer_id(),
                v.get_make(),
                v.get_model(),
                v.get_year(),
                v.get_vin(),
                v.get_license_plate(),
                v.get_color()
            };
            model.addRow(row);
        }
    }
}

class ButtonRendererVehicle extends JButton implements TableCellRenderer {
    private final JPanel panel;
    private final JButton btnDelete;
    
    public ButtonRendererVehicle() {
        panel = new JPanel(new FlowLayout(FlowLayout.CENTER, 5, 0)); 

        btnDelete = new JButton("Delete");
        btnDelete.setFont(new Font("Segoe UI", Font.BOLD, 12));
        btnDelete.setBackground(new Color(220, 53, 69)); 
        btnDelete.setForeground(Color.WHITE);
        btnDelete.setFocusPainted(false);
        btnDelete.setMargin(new Insets(2, 5, 2, 5)); 

        panel.add(btnDelete);
        panel.setBackground(null); 
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {
        if (isSelected) {
            panel.setBackground(table.getSelectionBackground());
        } else {
            panel.setBackground(table.getBackground());
        }
        return panel;
    }
}

// Makes the button clickable
class ButtonEditorVehicle extends DefaultCellEditor {
    private final JPanel panel;
    private final JButton btnDelete;
    private final JTable table;
    private final vehiclePanel vehiclePanel;
    private int selectedRow;
    
    public ButtonEditorVehicle(JCheckBox checkBox, JTable table, vehiclePanel vehiclePanel) {
        super(checkBox);
        this.table = table;
        this.vehiclePanel = vehiclePanel;
        panel = new JPanel(new FlowLayout(FlowLayout.CENTER, 5, 0));
        
        btnDelete = new JButton("Delete");
        btnDelete.setFont(new Font("Segoe UI", Font.BOLD, 12));
        btnDelete.setBackground(new Color(220, 53, 69));
        btnDelete.setForeground(Color.WHITE);
        btnDelete.setFocusPainted(false);
        btnDelete.setMargin(new Insets(2, 5, 2, 5));
        
        btnDelete.addActionListener(e -> {
            fireEditingStopped();
            
            try {
                if (selectedRow < 0 || selectedRow >= table.getRowCount()) {
                    JOptionPane.showMessageDialog(
                        SwingUtilities.getWindowAncestor(table),
                        "Invalid row selection.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                    );
                    return;
                }
                
                int id = (int) table.getValueAt(selectedRow, 0);
                
                int response = JOptionPane.showConfirmDialog(
                    SwingUtilities.getWindowAncestor(table),
                    "Are you sure you want to delete vehicle: " + id + "?",
                    "Confirm Deletion",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
                );
                
                if (response == JOptionPane.YES_OPTION) {
                    //Vehicle.delete_vehicle(id);
                    
                    //DefaultTableModel model = (DefaultTableModel) table.getModel();
                    //model.removeRow(selectedRow);
                    
                    boolean dbSuccess = Vehicle.deleteVehicleFromDB(id);
                    if (!dbSuccess) {
                        JOptionPane.showMessageDialog(
                            SwingUtilities.getWindowAncestor(table),
                            "Failed to delete vehicle from database!",
                            "Database Error",
                            JOptionPane.ERROR_MESSAGE
                        );
                    }
                    
                    System.out.println("Deleted vehicle with ID: " + id);
                    
                    vehiclePanel.updateTable();
                    
                    //table.revalidate();
                    //table.repaint();
                }
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(
                    SwingUtilities.getWindowAncestor(table),
                    "Error deleting vehicle: " + ex.getMessage(),
                    "Deletion Error",
                    JOptionPane.ERROR_MESSAGE
                );
                ex.printStackTrace();
            }
        });
        
        panel.add(btnDelete);
        panel.setBackground(null);
    }
    
    @Override
    public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
        this.selectedRow = row;
        
        if (isSelected) {
            panel.setBackground(table.getSelectionBackground());
        } else {
            panel.setBackground(table.getBackground());
        }
        
        return panel;
    }
    
    @Override
    public Object getCellEditorValue() {
        return "";
    }
    
    @Override
    public boolean stopCellEditing() {
        return super.stopCellEditing();
    }
}
