/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.carrepairservicemanagementsystem;

import com.mycompany.carrepairservicemanagementsystem.db.DBConnection;
import com.mycompany.carrepairservicemanagementsystem.models.Customer;
import com.mycompany.carrepairservicemanagementsystem.models.Inventory;
import com.mycompany.carrepairservicemanagementsystem.models.OrderItem;
import com.mycompany.carrepairservicemanagementsystem.models.ServiceOrder;
import com.mycompany.carrepairservicemanagementsystem.models.Vehicle;
import com.mycompany.carrepairservicemanagementsystem.panels.customerPanel;
import com.mycompany.carrepairservicemanagementsystem.panels.inventoryPanel;
import com.mycompany.carrepairservicemanagementsystem.panels.orderItemPanel;
import com.mycompany.carrepairservicemanagementsystem.panels.serviceOrderPanel;
import com.mycompany.carrepairservicemanagementsystem.panels.vehiclePanel;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author emiryncr
 */
public class ManagementDashboard extends javax.swing.JFrame {
    private customerPanel customerPanel;
    private vehiclePanel vehiclePanel;
    private serviceOrderPanel serviceOrderPanel;
    private orderItemPanel orderItemPanel;
    private inventoryPanel inventoryPanel;

    public ManagementDashboard() {
        
        Connection conn = DBConnection.getConnection();
        if(conn == null){
            JOptionPane.showMessageDialog(null, "Database connection could not be established!", "Connection failure: ", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        
        initComponents();
        customerPanel = new customerPanel();
        vehiclePanel = new vehiclePanel();
        serviceOrderPanel = new serviceOrderPanel();
        orderItemPanel = new orderItemPanel();
        inventoryPanel = new inventoryPanel();
        mainTabbedPane.addTab("Customers", customerPanel);
        mainTabbedPane.addTab("Vehicles", vehiclePanel);
        mainTabbedPane.addTab("Inventory", inventoryPanel);
        mainTabbedPane.addTab("Services", serviceOrderPanel);
        mainTabbedPane.addTab("Order Items", orderItemPanel);
        
        customerPanel.updateTable();
        vehiclePanel.updateTable();
        serviceOrderPanel.updateTable();
        orderItemPanel.updateTable();
        inventoryPanel.updateTable();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mainTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        backupBtn = new javax.swing.JMenuItem();
        restoreBtn = new javax.swing.JMenuItem();
        deleteAllBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Car Repair Service Management System");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        mainTabbedPane.setBorder(new javax.swing.border.MatteBorder(null));

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(770, 360));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("💼 \"Managing Service, Simplifying Life.\"");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel2)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Dashboard", jPanel1);

        getContentPane().add(mainTabbedPane, java.awt.BorderLayout.CENTER);

        jMenu1.setText("System");

        backupBtn.setText("Backup for all");
        backupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupBtnActionPerformed(evt);
            }
        });
        jMenu1.add(backupBtn);

        restoreBtn.setText("Restore for all");
        restoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreBtnActionPerformed(evt);
            }
        });
        jMenu1.add(restoreBtn);

        deleteAllBtn.setText("Delete for all");
        deleteAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAllBtnActionPerformed(evt);
            }
        });
        jMenu1.add(deleteAllBtn);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupBtnActionPerformed
        // TODO add your handling code here:
        try {
            Customer.backupCustomersFromDB();
            Vehicle.backupVehiclesFromDB();
            Inventory.backupInventoryFromDB();
            ServiceOrder.backupServiceOrdersFromDB();
            OrderItem.backupOrderItemsFromDB();
            JOptionPane.showMessageDialog(this, "All data backed up successfully.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Backup failed: " + e.getMessage());
        }
    }//GEN-LAST:event_backupBtnActionPerformed

    private void restoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreBtnActionPerformed
        // TODO add your handling code here:
        try {
            Customer.restoreCustomersToDBFromFile();
            Vehicle.restoreVehiclesToDBFromFile();
            Inventory.restoreInventoryToDBFromFile();
            ServiceOrder.restoreServiceOrdersToDBFromFile();
            OrderItem.restoreOrderItemsToDBFromFile();
            JOptionPane.showMessageDialog(this, "All data restored successfully.");
            updateAllTables();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Restore failed: " + e.getMessage());
        }
    }//GEN-LAST:event_restoreBtnActionPerformed

    private void deleteAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAllBtnActionPerformed
        // TODO add your handling code here:
        try {
            OrderItem.deleteAllOrderItemsFromDB();
            ServiceOrder.deleteAllServiceOrdersFromDB();
            Inventory.deleteAllInventoryFromDB();
            Vehicle.deleteAllVehiclesFromDB();
            Customer.deleteAllCustomersFromDB();           
            JOptionPane.showMessageDialog(this, "All data deleted successfully.");
            updateAllTables();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "DSeletion failed: " + e.getMessage());
        }
        
    }//GEN-LAST:event_deleteAllBtnActionPerformed

    private void updateAllTables() {
        customerPanel.updateTable();
        vehiclePanel.updateTable();
        inventoryPanel.updateTable();
        serviceOrderPanel.updateTable();
        orderItemPanel.updateTable();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagementDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagementDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagementDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagementDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagementDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem backupBtn;
    private javax.swing.JMenuItem deleteAllBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JMenuItem restoreBtn;
    // End of variables declaration//GEN-END:variables
}
